AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'
    # Ignore code from test fixtures
    - 'spec/fixtures/**/*'

Lint/ConditionPosition:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Style/SpaceBeforeComment:
  Enabled: true

Metrics/ModuleLength:
  Enabled: false

# DISABLED - not useful
Style/HashSyntax:
  Enabled: true

# USES: as shortcut for non nil&valid checking a = x() and a.empty?
# DISABLED - not useful
Style/AndOr:
  Enabled: false

# DISABLED - not useful
Style/RedundantSelf:
  Enabled: false

# DISABLED - not useful
Style/WhileUntilModifier:
  Enabled: false

# DISABLED - the offender is just haskell envy
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# DISABLED
Lint/Eval:
  Enabled: false

# DISABLED
Lint/BlockAlignment:
  Enabled: true

# DISABLED
Lint/DefEndAlignment:
  Enabled: true

# DISABLED
Lint/EndAlignment:
  Enabled: true

# DISABLED
Lint/DeprecatedClassMethods:
  Enabled: false

# DISABLED
Lint/Loop:
  Enabled: false

# DISABLED
Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/Void:
  Enabled: true

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AlignArray:
  Enabled: true

Style/AlignHash:
  Enabled: true

Style/AlignParameters:
  Enabled: true

Metrics/BlockNesting:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: true

Style/CaseEquality:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassAndModuleCamelCase:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/WhenThen:
  Enabled: false

# DISABLED - not useful
Style/WordArray:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/Tab:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: true

Style/SpaceBeforeFirstArg:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundKeyword:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: false

Style/SpaceAfterNot:
  Enabled: false

Style/SpaceAfterSemicolon:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeComma:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ConstantName:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/DotPosition:
  Enabled: false

# DISABLED - used for converting to bool
Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/IndentArray:
  Enabled: true

Style/IndentHash:
  Enabled: true

Style/IndentationConsistency:
  Enabled: false

Style/IndentationWidth:
  Enabled: true

Style/EmptyLines:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/Next:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/FileName:
  Enabled: false

Style/For:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/RequireParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
